<?php


/**
 * This class defines the structure of the 'fare_request' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 12 00:34:49 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FareRequestTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FareRequestTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('fare_request');
		$this->setPhpName('FareRequest');
		$this->setClassname('FareRequest');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('fare_request_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('HASH', 'Hash', 'VARCHAR', true, 255, null);
		$this->addColumn('START_ADDRESS', 'StartAddress', 'VARCHAR', true, 255, null);
		$this->addColumn('FLIGHT_NUMBER', 'FlightNumber', 'VARCHAR', false, 100, null);
		$this->addColumn('END_ADDRESS', 'EndAddress', 'VARCHAR', true, 255, null);
		$this->addColumn('DATE', 'Date', 'DATE', true, null, null);
		$this->addColumn('TIME', 'Time', 'TIME', true, null, null);
		$this->addColumn('TAXI_CODE', 'TaxiCode', 'VARCHAR', false, 50, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // FareRequestTableMap
