<?php

/**
 * Base static class for performing query and update operations on the 'fare' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 12 00:34:49 2011
 *
 * @package    lib.model.om
 */
abstract class BaseFarePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'fare';

	/** the related Propel class for this table */
	const OM_CLASS = 'Fare';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Fare';

	/** the related TableMap class for this table */
	const TM_CLASS = 'FareTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 35;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'fare.ID';

	/** the column name for the HASH field */
	const HASH = 'fare.HASH';

	/** the column name for the DRIVER_ID field */
	const DRIVER_ID = 'fare.DRIVER_ID';

	/** the column name for the CUSTOMER_ID field */
	const CUSTOMER_ID = 'fare.CUSTOMER_ID';

	/** the column name for the START_ADDRESS field */
	const START_ADDRESS = 'fare.START_ADDRESS';

	/** the column name for the FLIGHT_NUMBER field */
	const FLIGHT_NUMBER = 'fare.FLIGHT_NUMBER';

	/** the column name for the START_LAT field */
	const START_LAT = 'fare.START_LAT';

	/** the column name for the START_LNG field */
	const START_LNG = 'fare.START_LNG';

	/** the column name for the END_ADDRESS field */
	const END_ADDRESS = 'fare.END_ADDRESS';

	/** the column name for the END_LAT field */
	const END_LAT = 'fare.END_LAT';

	/** the column name for the END_LNG field */
	const END_LNG = 'fare.END_LNG';

	/** the column name for the DATE field */
	const DATE = 'fare.DATE';

	/** the column name for the TIME field */
	const TIME = 'fare.TIME';

	/** the column name for the TAXI_CODE field */
	const TAXI_CODE = 'fare.TAXI_CODE';

	/** the column name for the DATETIME field */
	const DATETIME = 'fare.DATETIME';

	/** the column name for the DURATION field */
	const DURATION = 'fare.DURATION';

	/** the column name for the DISTANCE field */
	const DISTANCE = 'fare.DISTANCE';

	/** the column name for the REAL_START_LAT field */
	const REAL_START_LAT = 'fare.REAL_START_LAT';

	/** the column name for the REAL_START_LNG field */
	const REAL_START_LNG = 'fare.REAL_START_LNG';

	/** the column name for the REAL_END_LAT field */
	const REAL_END_LAT = 'fare.REAL_END_LAT';

	/** the column name for the REAL_END_LNG field */
	const REAL_END_LNG = 'fare.REAL_END_LNG';

	/** the column name for the REAL_DURATION field */
	const REAL_DURATION = 'fare.REAL_DURATION';

	/** the column name for the REAL_DISTANCE field */
	const REAL_DISTANCE = 'fare.REAL_DISTANCE';

	/** the column name for the PRICE field */
	const PRICE = 'fare.PRICE';

	/** the column name for the SUPPLEMENT field */
	const SUPPLEMENT = 'fare.SUPPLEMENT';

	/** the column name for the VAT field */
	const VAT = 'fare.VAT';

	/** the column name for the PRICE_INCLUDING_TAX field */
	const PRICE_INCLUDING_TAX = 'fare.PRICE_INCLUDING_TAX';

	/** the column name for the CONFIRMED field */
	const CONFIRMED = 'fare.CONFIRMED';

	/** the column name for the VALID field */
	const VALID = 'fare.VALID';

	/** the column name for the TAKEN field */
	const TAKEN = 'fare.TAKEN';

	/** the column name for the FINISHED field */
	const FINISHED = 'fare.FINISHED';

	/** the column name for the DONE field */
	const DONE = 'fare.DONE';

	/** the column name for the CUSTOMER_AVAILABLE field */
	const CUSTOMER_AVAILABLE = 'fare.CUSTOMER_AVAILABLE';

	/** the column name for the SPECIAL_REQUEST field */
	const SPECIAL_REQUEST = 'fare.SPECIAL_REQUEST';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'fare.CREATED_AT';

	/**
	 * An identiy map to hold any loaded instances of Fare objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Fare[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Hash', 'DriverId', 'CustomerId', 'StartAddress', 'FlightNumber', 'StartLat', 'StartLng', 'EndAddress', 'EndLat', 'EndLng', 'Date', 'Time', 'TaxiCode', 'Datetime', 'Duration', 'Distance', 'RealStartLat', 'RealStartLng', 'RealEndLat', 'RealEndLng', 'RealDuration', 'RealDistance', 'Price', 'Supplement', 'Vat', 'PriceIncludingTax', 'Confirmed', 'Valid', 'Taken', 'Finished', 'Done', 'CustomerAvailable', 'SpecialRequest', 'CreatedAt', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'hash', 'driverId', 'customerId', 'startAddress', 'flightNumber', 'startLat', 'startLng', 'endAddress', 'endLat', 'endLng', 'date', 'time', 'taxiCode', 'datetime', 'duration', 'distance', 'realStartLat', 'realStartLng', 'realEndLat', 'realEndLng', 'realDuration', 'realDistance', 'price', 'supplement', 'vat', 'priceIncludingTax', 'confirmed', 'valid', 'taken', 'finished', 'done', 'customerAvailable', 'specialRequest', 'createdAt', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::HASH, self::DRIVER_ID, self::CUSTOMER_ID, self::START_ADDRESS, self::FLIGHT_NUMBER, self::START_LAT, self::START_LNG, self::END_ADDRESS, self::END_LAT, self::END_LNG, self::DATE, self::TIME, self::TAXI_CODE, self::DATETIME, self::DURATION, self::DISTANCE, self::REAL_START_LAT, self::REAL_START_LNG, self::REAL_END_LAT, self::REAL_END_LNG, self::REAL_DURATION, self::REAL_DISTANCE, self::PRICE, self::SUPPLEMENT, self::VAT, self::PRICE_INCLUDING_TAX, self::CONFIRMED, self::VALID, self::TAKEN, self::FINISHED, self::DONE, self::CUSTOMER_AVAILABLE, self::SPECIAL_REQUEST, self::CREATED_AT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'hash', 'driver_id', 'customer_id', 'start_address', 'flight_number', 'start_lat', 'start_lng', 'end_address', 'end_lat', 'end_lng', 'date', 'time', 'taxi_code', 'datetime', 'duration', 'distance', 'real_start_lat', 'real_start_lng', 'real_end_lat', 'real_end_lng', 'real_duration', 'real_distance', 'price', 'supplement', 'vat', 'price_including_tax', 'confirmed', 'valid', 'taken', 'finished', 'done', 'customer_available', 'special_request', 'created_at', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Hash' => 1, 'DriverId' => 2, 'CustomerId' => 3, 'StartAddress' => 4, 'FlightNumber' => 5, 'StartLat' => 6, 'StartLng' => 7, 'EndAddress' => 8, 'EndLat' => 9, 'EndLng' => 10, 'Date' => 11, 'Time' => 12, 'TaxiCode' => 13, 'Datetime' => 14, 'Duration' => 15, 'Distance' => 16, 'RealStartLat' => 17, 'RealStartLng' => 18, 'RealEndLat' => 19, 'RealEndLng' => 20, 'RealDuration' => 21, 'RealDistance' => 22, 'Price' => 23, 'Supplement' => 24, 'Vat' => 25, 'PriceIncludingTax' => 26, 'Confirmed' => 27, 'Valid' => 28, 'Taken' => 29, 'Finished' => 30, 'Done' => 31, 'CustomerAvailable' => 32, 'SpecialRequest' => 33, 'CreatedAt' => 34, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'hash' => 1, 'driverId' => 2, 'customerId' => 3, 'startAddress' => 4, 'flightNumber' => 5, 'startLat' => 6, 'startLng' => 7, 'endAddress' => 8, 'endLat' => 9, 'endLng' => 10, 'date' => 11, 'time' => 12, 'taxiCode' => 13, 'datetime' => 14, 'duration' => 15, 'distance' => 16, 'realStartLat' => 17, 'realStartLng' => 18, 'realEndLat' => 19, 'realEndLng' => 20, 'realDuration' => 21, 'realDistance' => 22, 'price' => 23, 'supplement' => 24, 'vat' => 25, 'priceIncludingTax' => 26, 'confirmed' => 27, 'valid' => 28, 'taken' => 29, 'finished' => 30, 'done' => 31, 'customerAvailable' => 32, 'specialRequest' => 33, 'createdAt' => 34, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::HASH => 1, self::DRIVER_ID => 2, self::CUSTOMER_ID => 3, self::START_ADDRESS => 4, self::FLIGHT_NUMBER => 5, self::START_LAT => 6, self::START_LNG => 7, self::END_ADDRESS => 8, self::END_LAT => 9, self::END_LNG => 10, self::DATE => 11, self::TIME => 12, self::TAXI_CODE => 13, self::DATETIME => 14, self::DURATION => 15, self::DISTANCE => 16, self::REAL_START_LAT => 17, self::REAL_START_LNG => 18, self::REAL_END_LAT => 19, self::REAL_END_LNG => 20, self::REAL_DURATION => 21, self::REAL_DISTANCE => 22, self::PRICE => 23, self::SUPPLEMENT => 24, self::VAT => 25, self::PRICE_INCLUDING_TAX => 26, self::CONFIRMED => 27, self::VALID => 28, self::TAKEN => 29, self::FINISHED => 30, self::DONE => 31, self::CUSTOMER_AVAILABLE => 32, self::SPECIAL_REQUEST => 33, self::CREATED_AT => 34, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'hash' => 1, 'driver_id' => 2, 'customer_id' => 3, 'start_address' => 4, 'flight_number' => 5, 'start_lat' => 6, 'start_lng' => 7, 'end_address' => 8, 'end_lat' => 9, 'end_lng' => 10, 'date' => 11, 'time' => 12, 'taxi_code' => 13, 'datetime' => 14, 'duration' => 15, 'distance' => 16, 'real_start_lat' => 17, 'real_start_lng' => 18, 'real_end_lat' => 19, 'real_end_lng' => 20, 'real_duration' => 21, 'real_distance' => 22, 'price' => 23, 'supplement' => 24, 'vat' => 25, 'price_including_tax' => 26, 'confirmed' => 27, 'valid' => 28, 'taken' => 29, 'finished' => 30, 'done' => 31, 'customer_available' => 32, 'special_request' => 33, 'created_at' => 34, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. FarePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(FarePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(FarePeer::ID);
		$criteria->addSelectColumn(FarePeer::HASH);
		$criteria->addSelectColumn(FarePeer::DRIVER_ID);
		$criteria->addSelectColumn(FarePeer::CUSTOMER_ID);
		$criteria->addSelectColumn(FarePeer::START_ADDRESS);
		$criteria->addSelectColumn(FarePeer::FLIGHT_NUMBER);
		$criteria->addSelectColumn(FarePeer::START_LAT);
		$criteria->addSelectColumn(FarePeer::START_LNG);
		$criteria->addSelectColumn(FarePeer::END_ADDRESS);
		$criteria->addSelectColumn(FarePeer::END_LAT);
		$criteria->addSelectColumn(FarePeer::END_LNG);
		$criteria->addSelectColumn(FarePeer::DATE);
		$criteria->addSelectColumn(FarePeer::TIME);
		$criteria->addSelectColumn(FarePeer::TAXI_CODE);
		$criteria->addSelectColumn(FarePeer::DATETIME);
		$criteria->addSelectColumn(FarePeer::DURATION);
		$criteria->addSelectColumn(FarePeer::DISTANCE);
		$criteria->addSelectColumn(FarePeer::REAL_START_LAT);
		$criteria->addSelectColumn(FarePeer::REAL_START_LNG);
		$criteria->addSelectColumn(FarePeer::REAL_END_LAT);
		$criteria->addSelectColumn(FarePeer::REAL_END_LNG);
		$criteria->addSelectColumn(FarePeer::REAL_DURATION);
		$criteria->addSelectColumn(FarePeer::REAL_DISTANCE);
		$criteria->addSelectColumn(FarePeer::PRICE);
		$criteria->addSelectColumn(FarePeer::SUPPLEMENT);
		$criteria->addSelectColumn(FarePeer::VAT);
		$criteria->addSelectColumn(FarePeer::PRICE_INCLUDING_TAX);
		$criteria->addSelectColumn(FarePeer::CONFIRMED);
		$criteria->addSelectColumn(FarePeer::VALID);
		$criteria->addSelectColumn(FarePeer::TAKEN);
		$criteria->addSelectColumn(FarePeer::FINISHED);
		$criteria->addSelectColumn(FarePeer::DONE);
		$criteria->addSelectColumn(FarePeer::CUSTOMER_AVAILABLE);
		$criteria->addSelectColumn(FarePeer::SPECIAL_REQUEST);
		$criteria->addSelectColumn(FarePeer::CREATED_AT);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Fare
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = FarePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return FarePeer::populateObjects(FarePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			FarePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Fare $value A Fare object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Fare $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Fare object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Fare) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Fare object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Fare Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to fare
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
		// invalidate objects in UserUnavailabilityPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		UserUnavailabilityPeer::clearInstancePool();

	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = FarePeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = FarePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				FarePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Driver table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinDriver(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related DriverCustomer table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinDriverCustomer(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Fare objects pre-filled with their Driver objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Fare objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinDriver(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		FarePeer::addSelectColumns($criteria);
		$startcol = (FarePeer::NUM_COLUMNS - FarePeer::NUM_LAZY_LOAD_COLUMNS);
		DriverPeer::addSelectColumns($criteria);

		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FarePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = FarePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				FarePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = DriverPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = DriverPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = DriverPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					DriverPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Fare) to $obj2 (Driver)
				$obj2->addFare($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Fare objects pre-filled with their DriverCustomer objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Fare objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinDriverCustomer(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		FarePeer::addSelectColumns($criteria);
		$startcol = (FarePeer::NUM_COLUMNS - FarePeer::NUM_LAZY_LOAD_COLUMNS);
		DriverCustomerPeer::addSelectColumns($criteria);

		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FarePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = FarePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				FarePeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = DriverCustomerPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = DriverCustomerPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = DriverCustomerPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					DriverCustomerPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded
				
				// Add the $obj1 (Fare) to $obj2 (DriverCustomer)
				$obj2->addFare($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Fare objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Fare objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		FarePeer::addSelectColumns($criteria);
		$startcol2 = (FarePeer::NUM_COLUMNS - FarePeer::NUM_LAZY_LOAD_COLUMNS);

		DriverPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (DriverPeer::NUM_COLUMNS - DriverPeer::NUM_LAZY_LOAD_COLUMNS);

		DriverCustomerPeer::addSelectColumns($criteria);
		$startcol4 = $startcol3 + (DriverCustomerPeer::NUM_COLUMNS - DriverCustomerPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FarePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = FarePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				FarePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Driver rows

			$key2 = DriverPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = DriverPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = DriverPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					DriverPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Fare) to the collection in $obj2 (Driver)
				$obj2->addFare($obj1);
			} // if joined row not null

			// Add objects for joined DriverCustomer rows

			$key3 = DriverCustomerPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = DriverCustomerPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$cls = DriverCustomerPeer::getOMClass(false);

					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					DriverCustomerPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Fare) to the collection in $obj3 (DriverCustomer)
				$obj3->addFare($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Driver table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptDriver(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related DriverCustomer table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptDriverCustomer(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FarePeer::TABLE_NAME);
		
		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FarePeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY should not affect count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Fare objects pre-filled with all related objects except Driver.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Fare objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptDriver(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		FarePeer::addSelectColumns($criteria);
		$startcol2 = (FarePeer::NUM_COLUMNS - FarePeer::NUM_LAZY_LOAD_COLUMNS);

		DriverCustomerPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (DriverCustomerPeer::NUM_COLUMNS - DriverCustomerPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(FarePeer::CUSTOMER_ID, DriverCustomerPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FarePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = FarePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				FarePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined DriverCustomer rows

				$key2 = DriverCustomerPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = DriverCustomerPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = DriverCustomerPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					DriverCustomerPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Fare) to the collection in $obj2 (DriverCustomer)
				$obj2->addFare($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Fare objects pre-filled with all related objects except DriverCustomer.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Fare objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptDriverCustomer(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		// $criteria->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		FarePeer::addSelectColumns($criteria);
		$startcol2 = (FarePeer::NUM_COLUMNS - FarePeer::NUM_LAZY_LOAD_COLUMNS);

		DriverPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (DriverPeer::NUM_COLUMNS - DriverPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(FarePeer::DRIVER_ID, DriverPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseFarePeer', $criteria, $con);
		}


		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FarePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FarePeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = FarePeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				FarePeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Driver rows

				$key2 = DriverPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = DriverPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$cls = DriverPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					DriverPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Fare) to the collection in $obj2 (Driver)
				$obj2->addFare($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseFarePeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseFarePeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new FareTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? FarePeer::CLASS_DEFAULT : FarePeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Fare or Criteria object.
	 *
	 * @param      mixed $values Criteria or Fare object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseFarePeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseFarePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Fare object
		}

		if ($criteria->containsKey(FarePeer::ID) && $criteria->keyContainsValue(FarePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.FarePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseFarePeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseFarePeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Fare or Criteria object.
	 *
	 * @param      mixed $values Criteria or Fare object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseFarePeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseFarePeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(FarePeer::ID);
			$selectCriteria->add(FarePeer::ID, $criteria->remove(FarePeer::ID), $comparison);

		} else { // $values is Fare object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BaseFarePeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BaseFarePeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the fare table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += FarePeer::doOnDeleteCascade(new Criteria(FarePeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(FarePeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			FarePeer::clearInstancePool();
			FarePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Fare or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Fare object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Fare) { // it's a model object
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(FarePeer::ID, (array) $values, Criteria::IN);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += FarePeer::doOnDeleteCascade($criteria, $con);
			
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			if ($values instanceof Criteria) {
				FarePeer::clearInstancePool();
			} elseif ($values instanceof Fare) { // it's a model object
				FarePeer::removeInstanceFromPool($values);
			} else { // it's a primary key, or an array of pks
				foreach ((array) $values as $singleval) {
					FarePeer::removeInstanceFromPool($singleval);
				}
			}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			FarePeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = FarePeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related UserUnavailability objects
			$criteria = new Criteria(UserUnavailabilityPeer::DATABASE_NAME);
			
			$criteria->add(UserUnavailabilityPeer::FARE_ID, $obj->getId());
			$affectedRows += UserUnavailabilityPeer::doDelete($criteria, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given Fare object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Fare $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Fare $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(FarePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(FarePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(FarePeer::DATABASE_NAME, FarePeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Fare
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = FarePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(FarePeer::DATABASE_NAME);
		$criteria->add(FarePeer::ID, $pk);

		$v = FarePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FarePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(FarePeer::DATABASE_NAME);
			$criteria->add(FarePeer::ID, $pks, Criteria::IN);
			$objs = FarePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseFarePeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseFarePeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseFarePeer::buildTableMap();

