<?php

/**
 * Base class that represents a row from the 'driver' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 12 00:34:48 2011
 *
 * @package    lib.model.om
 */
abstract class BaseDriver extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        DriverPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the first_name field.
	 * @var        string
	 */
	protected $first_name;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the phone field.
	 * @var        string
	 */
	protected $phone;

	/**
	 * The value for the taxi_code field.
	 * @var        string
	 */
	protected $taxi_code;

	/**
	 * The value for the hq field.
	 * @var        string
	 */
	protected $hq;

	/**
	 * The value for the hq_lat field.
	 * @var        string
	 */
	protected $hq_lat;

	/**
	 * The value for the hq_lng field.
	 * @var        string
	 */
	protected $hq_lng;

	/**
	 * The value for the hq_area field.
	 * @var        int
	 */
	protected $hq_area;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * @var        array DriverNotification[] Collection to store aggregation of DriverNotification objects.
	 */
	protected $collDriverNotifications;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDriverNotifications.
	 */
	private $lastDriverNotificationCriteria = null;

	/**
	 * @var        array DriverCustomer[] Collection to store aggregation of DriverCustomer objects.
	 */
	protected $collDriverCustomers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDriverCustomers.
	 */
	private $lastDriverCustomerCriteria = null;

	/**
	 * @var        array DriverAccount[] Collection to store aggregation of DriverAccount objects.
	 */
	protected $collDriverAccounts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDriverAccounts.
	 */
	private $lastDriverAccountCriteria = null;

	/**
	 * @var        array Fare[] Collection to store aggregation of Fare objects.
	 */
	protected $collFares;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFares.
	 */
	private $lastFareCriteria = null;

	/**
	 * @var        array Prime[] Collection to store aggregation of Prime objects.
	 */
	protected $collPrimesRelatedByDriverId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPrimesRelatedByDriverId.
	 */
	private $lastPrimeRelatedByDriverIdCriteria = null;

	/**
	 * @var        array Prime[] Collection to store aggregation of Prime objects.
	 */
	protected $collPrimesRelatedByPayerId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPrimesRelatedByPayerId.
	 */
	private $lastPrimeRelatedByPayerIdCriteria = null;

	/**
	 * @var        array Participation[] Collection to store aggregation of Participation objects.
	 */
	protected $collParticipations;

	/**
	 * @var        Criteria The criteria used to select the current contents of collParticipations.
	 */
	private $lastParticipationCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'DriverPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFirstName()
	{
		return $this->first_name;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [phone] column value.
	 * 
	 * @return     string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Get the [taxi_code] column value.
	 * 
	 * @return     string
	 */
	public function getTaxiCode()
	{
		return $this->taxi_code;
	}

	/**
	 * Get the [hq] column value.
	 * 
	 * @return     string
	 */
	public function getHq()
	{
		return $this->hq;
	}

	/**
	 * Get the [hq_lat] column value.
	 * 
	 * @return     string
	 */
	public function getHqLat()
	{
		return $this->hq_lat;
	}

	/**
	 * Get the [hq_lng] column value.
	 * 
	 * @return     string
	 */
	public function getHqLng()
	{
		return $this->hq_lng;
	}

	/**
	 * Get the [hq_area] column value.
	 * 
	 * @return     int
	 */
	public function getHqArea()
	{
		return $this->hq_area;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = DriverPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = DriverPeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = DriverPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->first_name !== $v) {
			$this->first_name = $v;
			$this->modifiedColumns[] = DriverPeer::FIRST_NAME;
		}

		return $this;
	} // setFirstName()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = DriverPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->phone !== $v) {
			$this->phone = $v;
			$this->modifiedColumns[] = DriverPeer::PHONE;
		}

		return $this;
	} // setPhone()

	/**
	 * Set the value of [taxi_code] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setTaxiCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->taxi_code !== $v) {
			$this->taxi_code = $v;
			$this->modifiedColumns[] = DriverPeer::TAXI_CODE;
		}

		return $this;
	} // setTaxiCode()

	/**
	 * Set the value of [hq] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setHq($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->hq !== $v) {
			$this->hq = $v;
			$this->modifiedColumns[] = DriverPeer::HQ;
		}

		return $this;
	} // setHq()

	/**
	 * Set the value of [hq_lat] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setHqLat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->hq_lat !== $v) {
			$this->hq_lat = $v;
			$this->modifiedColumns[] = DriverPeer::HQ_LAT;
		}

		return $this;
	} // setHqLat()

	/**
	 * Set the value of [hq_lng] column.
	 * 
	 * @param      string $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setHqLng($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->hq_lng !== $v) {
			$this->hq_lng = $v;
			$this->modifiedColumns[] = DriverPeer::HQ_LNG;
		}

		return $this;
	} // setHqLng()

	/**
	 * Set the value of [hq_area] column.
	 * 
	 * @param      int $v new value
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setHqArea($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->hq_area !== $v) {
			$this->hq_area = $v;
			$this->modifiedColumns[] = DriverPeer::HQ_AREA;
		}

		return $this;
	} // setHqArea()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Driver The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = DriverPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->first_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->phone = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->taxi_code = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->hq = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->hq_lat = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->hq_lng = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->hq_area = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->created_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = DriverPeer::NUM_COLUMNS - DriverPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Driver object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DriverPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = DriverPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUser = null;
			$this->collDriverNotifications = null;
			$this->lastDriverNotificationCriteria = null;

			$this->collDriverCustomers = null;
			$this->lastDriverCustomerCriteria = null;

			$this->collDriverAccounts = null;
			$this->lastDriverAccountCriteria = null;

			$this->collFares = null;
			$this->lastFareCriteria = null;

			$this->collPrimesRelatedByDriverId = null;
			$this->lastPrimeRelatedByDriverIdCriteria = null;

			$this->collPrimesRelatedByPayerId = null;
			$this->lastPrimeRelatedByPayerIdCriteria = null;

			$this->collParticipations = null;
			$this->lastParticipationCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DriverPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDriver:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				DriverPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDriver:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DriverPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDriver:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(DriverPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDriver:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				DriverPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = DriverPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = DriverPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += DriverPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collDriverNotifications !== null) {
				foreach ($this->collDriverNotifications as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDriverCustomers !== null) {
				foreach ($this->collDriverCustomers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDriverAccounts !== null) {
				foreach ($this->collDriverAccounts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFares !== null) {
				foreach ($this->collFares as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPrimesRelatedByDriverId !== null) {
				foreach ($this->collPrimesRelatedByDriverId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPrimesRelatedByPayerId !== null) {
				foreach ($this->collPrimesRelatedByPayerId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collParticipations !== null) {
				foreach ($this->collParticipations as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}


			if (($retval = DriverPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collDriverNotifications !== null) {
					foreach ($this->collDriverNotifications as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDriverCustomers !== null) {
					foreach ($this->collDriverCustomers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDriverAccounts !== null) {
					foreach ($this->collDriverAccounts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFares !== null) {
					foreach ($this->collFares as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPrimesRelatedByDriverId !== null) {
					foreach ($this->collPrimesRelatedByDriverId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPrimesRelatedByPayerId !== null) {
					foreach ($this->collPrimesRelatedByPayerId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collParticipations !== null) {
					foreach ($this->collParticipations as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DriverPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserId();
				break;
			case 2:
				return $this->getName();
				break;
			case 3:
				return $this->getFirstName();
				break;
			case 4:
				return $this->getEmail();
				break;
			case 5:
				return $this->getPhone();
				break;
			case 6:
				return $this->getTaxiCode();
				break;
			case 7:
				return $this->getHq();
				break;
			case 8:
				return $this->getHqLat();
				break;
			case 9:
				return $this->getHqLng();
				break;
			case 10:
				return $this->getHqArea();
				break;
			case 11:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = DriverPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserId(),
			$keys[2] => $this->getName(),
			$keys[3] => $this->getFirstName(),
			$keys[4] => $this->getEmail(),
			$keys[5] => $this->getPhone(),
			$keys[6] => $this->getTaxiCode(),
			$keys[7] => $this->getHq(),
			$keys[8] => $this->getHqLat(),
			$keys[9] => $this->getHqLng(),
			$keys[10] => $this->getHqArea(),
			$keys[11] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DriverPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserId($value);
				break;
			case 2:
				$this->setName($value);
				break;
			case 3:
				$this->setFirstName($value);
				break;
			case 4:
				$this->setEmail($value);
				break;
			case 5:
				$this->setPhone($value);
				break;
			case 6:
				$this->setTaxiCode($value);
				break;
			case 7:
				$this->setHq($value);
				break;
			case 8:
				$this->setHqLat($value);
				break;
			case 9:
				$this->setHqLng($value);
				break;
			case 10:
				$this->setHqArea($value);
				break;
			case 11:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = DriverPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFirstName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPhone($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setTaxiCode($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setHq($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHqLat($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setHqLng($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setHqArea($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCreatedAt($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(DriverPeer::DATABASE_NAME);

		if ($this->isColumnModified(DriverPeer::ID)) $criteria->add(DriverPeer::ID, $this->id);
		if ($this->isColumnModified(DriverPeer::USER_ID)) $criteria->add(DriverPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(DriverPeer::NAME)) $criteria->add(DriverPeer::NAME, $this->name);
		if ($this->isColumnModified(DriverPeer::FIRST_NAME)) $criteria->add(DriverPeer::FIRST_NAME, $this->first_name);
		if ($this->isColumnModified(DriverPeer::EMAIL)) $criteria->add(DriverPeer::EMAIL, $this->email);
		if ($this->isColumnModified(DriverPeer::PHONE)) $criteria->add(DriverPeer::PHONE, $this->phone);
		if ($this->isColumnModified(DriverPeer::TAXI_CODE)) $criteria->add(DriverPeer::TAXI_CODE, $this->taxi_code);
		if ($this->isColumnModified(DriverPeer::HQ)) $criteria->add(DriverPeer::HQ, $this->hq);
		if ($this->isColumnModified(DriverPeer::HQ_LAT)) $criteria->add(DriverPeer::HQ_LAT, $this->hq_lat);
		if ($this->isColumnModified(DriverPeer::HQ_LNG)) $criteria->add(DriverPeer::HQ_LNG, $this->hq_lng);
		if ($this->isColumnModified(DriverPeer::HQ_AREA)) $criteria->add(DriverPeer::HQ_AREA, $this->hq_area);
		if ($this->isColumnModified(DriverPeer::CREATED_AT)) $criteria->add(DriverPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(DriverPeer::DATABASE_NAME);

		$criteria->add(DriverPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Driver (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setName($this->name);

		$copyObj->setFirstName($this->first_name);

		$copyObj->setEmail($this->email);

		$copyObj->setPhone($this->phone);

		$copyObj->setTaxiCode($this->taxi_code);

		$copyObj->setHq($this->hq);

		$copyObj->setHqLat($this->hq_lat);

		$copyObj->setHqLng($this->hq_lng);

		$copyObj->setHqArea($this->hq_area);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getDriverNotifications() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDriverNotification($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDriverCustomers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDriverCustomer($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDriverAccounts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDriverAccount($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFares() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFare($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPrimesRelatedByDriverId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPrimeRelatedByDriverId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPrimesRelatedByPayerId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPrimeRelatedByPayerId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getParticipations() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addParticipation($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Driver Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     DriverPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new DriverPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Driver The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addDriver($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$this->asfGuardUser = sfGuardUserPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addDrivers($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Clears out the collDriverNotifications collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDriverNotifications()
	 */
	public function clearDriverNotifications()
	{
		$this->collDriverNotifications = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDriverNotifications collection (array).
	 *
	 * By default this just sets the collDriverNotifications collection to an empty array (like clearcollDriverNotifications());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDriverNotifications()
	{
		$this->collDriverNotifications = array();
	}

	/**
	 * Gets an array of DriverNotification objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related DriverNotifications from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DriverNotification[]
	 * @throws     PropelException
	 */
	public function getDriverNotifications($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDriverNotifications === null) {
			if ($this->isNew()) {
			   $this->collDriverNotifications = array();
			} else {

				$criteria->add(DriverNotificationPeer::DRIVER_ID, $this->id);

				DriverNotificationPeer::addSelectColumns($criteria);
				$this->collDriverNotifications = DriverNotificationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DriverNotificationPeer::DRIVER_ID, $this->id);

				DriverNotificationPeer::addSelectColumns($criteria);
				if (!isset($this->lastDriverNotificationCriteria) || !$this->lastDriverNotificationCriteria->equals($criteria)) {
					$this->collDriverNotifications = DriverNotificationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDriverNotificationCriteria = $criteria;
		return $this->collDriverNotifications;
	}

	/**
	 * Returns the number of related DriverNotification objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DriverNotification objects.
	 * @throws     PropelException
	 */
	public function countDriverNotifications(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDriverNotifications === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DriverNotificationPeer::DRIVER_ID, $this->id);

				$count = DriverNotificationPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DriverNotificationPeer::DRIVER_ID, $this->id);

				if (!isset($this->lastDriverNotificationCriteria) || !$this->lastDriverNotificationCriteria->equals($criteria)) {
					$count = DriverNotificationPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDriverNotifications);
				}
			} else {
				$count = count($this->collDriverNotifications);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DriverNotification object to this object
	 * through the DriverNotification foreign key attribute.
	 *
	 * @param      DriverNotification $l DriverNotification
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDriverNotification(DriverNotification $l)
	{
		if ($this->collDriverNotifications === null) {
			$this->initDriverNotifications();
		}
		if (!in_array($l, $this->collDriverNotifications, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDriverNotifications, $l);
			$l->setDriver($this);
		}
	}

	/**
	 * Clears out the collDriverCustomers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDriverCustomers()
	 */
	public function clearDriverCustomers()
	{
		$this->collDriverCustomers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDriverCustomers collection (array).
	 *
	 * By default this just sets the collDriverCustomers collection to an empty array (like clearcollDriverCustomers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDriverCustomers()
	{
		$this->collDriverCustomers = array();
	}

	/**
	 * Gets an array of DriverCustomer objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related DriverCustomers from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DriverCustomer[]
	 * @throws     PropelException
	 */
	public function getDriverCustomers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDriverCustomers === null) {
			if ($this->isNew()) {
			   $this->collDriverCustomers = array();
			} else {

				$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

				DriverCustomerPeer::addSelectColumns($criteria);
				$this->collDriverCustomers = DriverCustomerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

				DriverCustomerPeer::addSelectColumns($criteria);
				if (!isset($this->lastDriverCustomerCriteria) || !$this->lastDriverCustomerCriteria->equals($criteria)) {
					$this->collDriverCustomers = DriverCustomerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDriverCustomerCriteria = $criteria;
		return $this->collDriverCustomers;
	}

	/**
	 * Returns the number of related DriverCustomer objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DriverCustomer objects.
	 * @throws     PropelException
	 */
	public function countDriverCustomers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDriverCustomers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

				$count = DriverCustomerPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

				if (!isset($this->lastDriverCustomerCriteria) || !$this->lastDriverCustomerCriteria->equals($criteria)) {
					$count = DriverCustomerPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDriverCustomers);
				}
			} else {
				$count = count($this->collDriverCustomers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DriverCustomer object to this object
	 * through the DriverCustomer foreign key attribute.
	 *
	 * @param      DriverCustomer $l DriverCustomer
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDriverCustomer(DriverCustomer $l)
	{
		if ($this->collDriverCustomers === null) {
			$this->initDriverCustomers();
		}
		if (!in_array($l, $this->collDriverCustomers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDriverCustomers, $l);
			$l->setDriver($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related DriverCustomers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getDriverCustomersJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDriverCustomers === null) {
			if ($this->isNew()) {
				$this->collDriverCustomers = array();
			} else {

				$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

				$this->collDriverCustomers = DriverCustomerPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DriverCustomerPeer::DRIVER_ID, $this->id);

			if (!isset($this->lastDriverCustomerCriteria) || !$this->lastDriverCustomerCriteria->equals($criteria)) {
				$this->collDriverCustomers = DriverCustomerPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastDriverCustomerCriteria = $criteria;

		return $this->collDriverCustomers;
	}

	/**
	 * Clears out the collDriverAccounts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDriverAccounts()
	 */
	public function clearDriverAccounts()
	{
		$this->collDriverAccounts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDriverAccounts collection (array).
	 *
	 * By default this just sets the collDriverAccounts collection to an empty array (like clearcollDriverAccounts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDriverAccounts()
	{
		$this->collDriverAccounts = array();
	}

	/**
	 * Gets an array of DriverAccount objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related DriverAccounts from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DriverAccount[]
	 * @throws     PropelException
	 */
	public function getDriverAccounts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDriverAccounts === null) {
			if ($this->isNew()) {
			   $this->collDriverAccounts = array();
			} else {

				$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

				DriverAccountPeer::addSelectColumns($criteria);
				$this->collDriverAccounts = DriverAccountPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

				DriverAccountPeer::addSelectColumns($criteria);
				if (!isset($this->lastDriverAccountCriteria) || !$this->lastDriverAccountCriteria->equals($criteria)) {
					$this->collDriverAccounts = DriverAccountPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDriverAccountCriteria = $criteria;
		return $this->collDriverAccounts;
	}

	/**
	 * Returns the number of related DriverAccount objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DriverAccount objects.
	 * @throws     PropelException
	 */
	public function countDriverAccounts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDriverAccounts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

				$count = DriverAccountPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

				if (!isset($this->lastDriverAccountCriteria) || !$this->lastDriverAccountCriteria->equals($criteria)) {
					$count = DriverAccountPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDriverAccounts);
				}
			} else {
				$count = count($this->collDriverAccounts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DriverAccount object to this object
	 * through the DriverAccount foreign key attribute.
	 *
	 * @param      DriverAccount $l DriverAccount
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDriverAccount(DriverAccount $l)
	{
		if ($this->collDriverAccounts === null) {
			$this->initDriverAccounts();
		}
		if (!in_array($l, $this->collDriverAccounts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDriverAccounts, $l);
			$l->setDriver($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related DriverAccounts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getDriverAccountsJoinDriverAccountCategory($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDriverAccounts === null) {
			if ($this->isNew()) {
				$this->collDriverAccounts = array();
			} else {

				$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

				$this->collDriverAccounts = DriverAccountPeer::doSelectJoinDriverAccountCategory($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(DriverAccountPeer::DRIVER_ID, $this->id);

			if (!isset($this->lastDriverAccountCriteria) || !$this->lastDriverAccountCriteria->equals($criteria)) {
				$this->collDriverAccounts = DriverAccountPeer::doSelectJoinDriverAccountCategory($criteria, $con, $join_behavior);
			}
		}
		$this->lastDriverAccountCriteria = $criteria;

		return $this->collDriverAccounts;
	}

	/**
	 * Clears out the collFares collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFares()
	 */
	public function clearFares()
	{
		$this->collFares = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFares collection (array).
	 *
	 * By default this just sets the collFares collection to an empty array (like clearcollFares());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFares()
	{
		$this->collFares = array();
	}

	/**
	 * Gets an array of Fare objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related Fares from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Fare[]
	 * @throws     PropelException
	 */
	public function getFares($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFares === null) {
			if ($this->isNew()) {
			   $this->collFares = array();
			} else {

				$criteria->add(FarePeer::DRIVER_ID, $this->id);

				FarePeer::addSelectColumns($criteria);
				$this->collFares = FarePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FarePeer::DRIVER_ID, $this->id);

				FarePeer::addSelectColumns($criteria);
				if (!isset($this->lastFareCriteria) || !$this->lastFareCriteria->equals($criteria)) {
					$this->collFares = FarePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFareCriteria = $criteria;
		return $this->collFares;
	}

	/**
	 * Returns the number of related Fare objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Fare objects.
	 * @throws     PropelException
	 */
	public function countFares(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFares === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FarePeer::DRIVER_ID, $this->id);

				$count = FarePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FarePeer::DRIVER_ID, $this->id);

				if (!isset($this->lastFareCriteria) || !$this->lastFareCriteria->equals($criteria)) {
					$count = FarePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFares);
				}
			} else {
				$count = count($this->collFares);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Fare object to this object
	 * through the Fare foreign key attribute.
	 *
	 * @param      Fare $l Fare
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFare(Fare $l)
	{
		if ($this->collFares === null) {
			$this->initFares();
		}
		if (!in_array($l, $this->collFares, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFares, $l);
			$l->setDriver($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related Fares from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getFaresJoinDriverCustomer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFares === null) {
			if ($this->isNew()) {
				$this->collFares = array();
			} else {

				$criteria->add(FarePeer::DRIVER_ID, $this->id);

				$this->collFares = FarePeer::doSelectJoinDriverCustomer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FarePeer::DRIVER_ID, $this->id);

			if (!isset($this->lastFareCriteria) || !$this->lastFareCriteria->equals($criteria)) {
				$this->collFares = FarePeer::doSelectJoinDriverCustomer($criteria, $con, $join_behavior);
			}
		}
		$this->lastFareCriteria = $criteria;

		return $this->collFares;
	}

	/**
	 * Clears out the collPrimesRelatedByDriverId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPrimesRelatedByDriverId()
	 */
	public function clearPrimesRelatedByDriverId()
	{
		$this->collPrimesRelatedByDriverId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPrimesRelatedByDriverId collection (array).
	 *
	 * By default this just sets the collPrimesRelatedByDriverId collection to an empty array (like clearcollPrimesRelatedByDriverId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPrimesRelatedByDriverId()
	{
		$this->collPrimesRelatedByDriverId = array();
	}

	/**
	 * Gets an array of Prime objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related PrimesRelatedByDriverId from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Prime[]
	 * @throws     PropelException
	 */
	public function getPrimesRelatedByDriverId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPrimesRelatedByDriverId === null) {
			if ($this->isNew()) {
			   $this->collPrimesRelatedByDriverId = array();
			} else {

				$criteria->add(PrimePeer::DRIVER_ID, $this->id);

				PrimePeer::addSelectColumns($criteria);
				$this->collPrimesRelatedByDriverId = PrimePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PrimePeer::DRIVER_ID, $this->id);

				PrimePeer::addSelectColumns($criteria);
				if (!isset($this->lastPrimeRelatedByDriverIdCriteria) || !$this->lastPrimeRelatedByDriverIdCriteria->equals($criteria)) {
					$this->collPrimesRelatedByDriverId = PrimePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPrimeRelatedByDriverIdCriteria = $criteria;
		return $this->collPrimesRelatedByDriverId;
	}

	/**
	 * Returns the number of related Prime objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Prime objects.
	 * @throws     PropelException
	 */
	public function countPrimesRelatedByDriverId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPrimesRelatedByDriverId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PrimePeer::DRIVER_ID, $this->id);

				$count = PrimePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PrimePeer::DRIVER_ID, $this->id);

				if (!isset($this->lastPrimeRelatedByDriverIdCriteria) || !$this->lastPrimeRelatedByDriverIdCriteria->equals($criteria)) {
					$count = PrimePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPrimesRelatedByDriverId);
				}
			} else {
				$count = count($this->collPrimesRelatedByDriverId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Prime object to this object
	 * through the Prime foreign key attribute.
	 *
	 * @param      Prime $l Prime
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPrimeRelatedByDriverId(Prime $l)
	{
		if ($this->collPrimesRelatedByDriverId === null) {
			$this->initPrimesRelatedByDriverId();
		}
		if (!in_array($l, $this->collPrimesRelatedByDriverId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPrimesRelatedByDriverId, $l);
			$l->setDriverRelatedByDriverId($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related PrimesRelatedByDriverId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getPrimesRelatedByDriverIdJoinFare($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPrimesRelatedByDriverId === null) {
			if ($this->isNew()) {
				$this->collPrimesRelatedByDriverId = array();
			} else {

				$criteria->add(PrimePeer::DRIVER_ID, $this->id);

				$this->collPrimesRelatedByDriverId = PrimePeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PrimePeer::DRIVER_ID, $this->id);

			if (!isset($this->lastPrimeRelatedByDriverIdCriteria) || !$this->lastPrimeRelatedByDriverIdCriteria->equals($criteria)) {
				$this->collPrimesRelatedByDriverId = PrimePeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		}
		$this->lastPrimeRelatedByDriverIdCriteria = $criteria;

		return $this->collPrimesRelatedByDriverId;
	}

	/**
	 * Clears out the collPrimesRelatedByPayerId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPrimesRelatedByPayerId()
	 */
	public function clearPrimesRelatedByPayerId()
	{
		$this->collPrimesRelatedByPayerId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPrimesRelatedByPayerId collection (array).
	 *
	 * By default this just sets the collPrimesRelatedByPayerId collection to an empty array (like clearcollPrimesRelatedByPayerId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPrimesRelatedByPayerId()
	{
		$this->collPrimesRelatedByPayerId = array();
	}

	/**
	 * Gets an array of Prime objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related PrimesRelatedByPayerId from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Prime[]
	 * @throws     PropelException
	 */
	public function getPrimesRelatedByPayerId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPrimesRelatedByPayerId === null) {
			if ($this->isNew()) {
			   $this->collPrimesRelatedByPayerId = array();
			} else {

				$criteria->add(PrimePeer::PAYER_ID, $this->id);

				PrimePeer::addSelectColumns($criteria);
				$this->collPrimesRelatedByPayerId = PrimePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PrimePeer::PAYER_ID, $this->id);

				PrimePeer::addSelectColumns($criteria);
				if (!isset($this->lastPrimeRelatedByPayerIdCriteria) || !$this->lastPrimeRelatedByPayerIdCriteria->equals($criteria)) {
					$this->collPrimesRelatedByPayerId = PrimePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPrimeRelatedByPayerIdCriteria = $criteria;
		return $this->collPrimesRelatedByPayerId;
	}

	/**
	 * Returns the number of related Prime objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Prime objects.
	 * @throws     PropelException
	 */
	public function countPrimesRelatedByPayerId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPrimesRelatedByPayerId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PrimePeer::PAYER_ID, $this->id);

				$count = PrimePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PrimePeer::PAYER_ID, $this->id);

				if (!isset($this->lastPrimeRelatedByPayerIdCriteria) || !$this->lastPrimeRelatedByPayerIdCriteria->equals($criteria)) {
					$count = PrimePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPrimesRelatedByPayerId);
				}
			} else {
				$count = count($this->collPrimesRelatedByPayerId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Prime object to this object
	 * through the Prime foreign key attribute.
	 *
	 * @param      Prime $l Prime
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPrimeRelatedByPayerId(Prime $l)
	{
		if ($this->collPrimesRelatedByPayerId === null) {
			$this->initPrimesRelatedByPayerId();
		}
		if (!in_array($l, $this->collPrimesRelatedByPayerId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPrimesRelatedByPayerId, $l);
			$l->setDriverRelatedByPayerId($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related PrimesRelatedByPayerId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getPrimesRelatedByPayerIdJoinFare($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPrimesRelatedByPayerId === null) {
			if ($this->isNew()) {
				$this->collPrimesRelatedByPayerId = array();
			} else {

				$criteria->add(PrimePeer::PAYER_ID, $this->id);

				$this->collPrimesRelatedByPayerId = PrimePeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PrimePeer::PAYER_ID, $this->id);

			if (!isset($this->lastPrimeRelatedByPayerIdCriteria) || !$this->lastPrimeRelatedByPayerIdCriteria->equals($criteria)) {
				$this->collPrimesRelatedByPayerId = PrimePeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		}
		$this->lastPrimeRelatedByPayerIdCriteria = $criteria;

		return $this->collPrimesRelatedByPayerId;
	}

	/**
	 * Clears out the collParticipations collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addParticipations()
	 */
	public function clearParticipations()
	{
		$this->collParticipations = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collParticipations collection (array).
	 *
	 * By default this just sets the collParticipations collection to an empty array (like clearcollParticipations());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initParticipations()
	{
		$this->collParticipations = array();
	}

	/**
	 * Gets an array of Participation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Driver has previously been saved, it will retrieve
	 * related Participations from storage. If this Driver is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Participation[]
	 * @throws     PropelException
	 */
	public function getParticipations($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collParticipations === null) {
			if ($this->isNew()) {
			   $this->collParticipations = array();
			} else {

				$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

				ParticipationPeer::addSelectColumns($criteria);
				$this->collParticipations = ParticipationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

				ParticipationPeer::addSelectColumns($criteria);
				if (!isset($this->lastParticipationCriteria) || !$this->lastParticipationCriteria->equals($criteria)) {
					$this->collParticipations = ParticipationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastParticipationCriteria = $criteria;
		return $this->collParticipations;
	}

	/**
	 * Returns the number of related Participation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Participation objects.
	 * @throws     PropelException
	 */
	public function countParticipations(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collParticipations === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

				$count = ParticipationPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

				if (!isset($this->lastParticipationCriteria) || !$this->lastParticipationCriteria->equals($criteria)) {
					$count = ParticipationPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collParticipations);
				}
			} else {
				$count = count($this->collParticipations);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Participation object to this object
	 * through the Participation foreign key attribute.
	 *
	 * @param      Participation $l Participation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addParticipation(Participation $l)
	{
		if ($this->collParticipations === null) {
			$this->initParticipations();
		}
		if (!in_array($l, $this->collParticipations, true)) { // only add it if the **same** object is not already associated
			array_push($this->collParticipations, $l);
			$l->setDriver($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Driver is new, it will return
	 * an empty collection; or if this Driver has previously
	 * been saved, it will retrieve related Participations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Driver.
	 */
	public function getParticipationsJoinFare($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(DriverPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collParticipations === null) {
			if ($this->isNew()) {
				$this->collParticipations = array();
			} else {

				$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

				$this->collParticipations = ParticipationPeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ParticipationPeer::DRIVER_ID, $this->id);

			if (!isset($this->lastParticipationCriteria) || !$this->lastParticipationCriteria->equals($criteria)) {
				$this->collParticipations = ParticipationPeer::doSelectJoinFare($criteria, $con, $join_behavior);
			}
		}
		$this->lastParticipationCriteria = $criteria;

		return $this->collParticipations;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collDriverNotifications) {
				foreach ((array) $this->collDriverNotifications as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDriverCustomers) {
				foreach ((array) $this->collDriverCustomers as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDriverAccounts) {
				foreach ((array) $this->collDriverAccounts as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFares) {
				foreach ((array) $this->collFares as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPrimesRelatedByDriverId) {
				foreach ((array) $this->collPrimesRelatedByDriverId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPrimesRelatedByPayerId) {
				foreach ((array) $this->collPrimesRelatedByPayerId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collParticipations) {
				foreach ((array) $this->collParticipations as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collDriverNotifications = null;
		$this->collDriverCustomers = null;
		$this->collDriverAccounts = null;
		$this->collFares = null;
		$this->collPrimesRelatedByDriverId = null;
		$this->collPrimesRelatedByPayerId = null;
		$this->collParticipations = null;
			$this->asfGuardUser = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseDriver:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseDriver::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseDriver
