<?php


/**
 * Skeleton subclass for performing query and update operations on the 'driver' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/01/11 10:34:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DriverPeer extends BaseDriverPeer {

    static function retrieveByTaxiCode($taxi_code) {
        $c = new Criteria();
        $c->add(DriverPeer::TAXI_CODE, $taxi_code);
        $driver = DriverPeer::doSelectOne($c);

        return $driver;
    }

} // DriverPeer
