<?php


/**
 * Skeleton subclass for performing query and update operations on the 'driver_customer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/01/11 10:34:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DriverCustomerPeer extends BaseDriverCustomerPeer {

  static public $genders = array(
    'm' => 'M.',
    'mme' => 'Mme',
    'mlle' => 'Mlle',
  );

  static public $phone_countries = array(
    '33' => 'France',
  );

} // DriverCustomerPeer
