<?php


/**
 * Skeleton subclass for representing a row from the 'driver_customer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/01/11 10:34:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DriverCustomer extends BaseDriverCustomer {

  public function __toString()
  {
    return $this->getName()." ".$this->getFirstName();
  }

  public function save(PropelPDO $con = null)
  {

    $this->setPhoneInternational($this->getPhoneCountry()."".substr($this->getPhoneNumber(), 1));

    if($this->isNew()) {


        $pass = Tools::generatePassword();
        $email = $this->getEmail();

        $user = new sfGuardUser();
        $user->setUsername($email);
        $user->setPassword($pass);
        $user->save();

        $user_group = new sfGuardUserGroup();
        $user_group->setGroupId(1);
        $user_group->setUserId($user->getId());
        $user_group->save();

        $this->setUserId($user->getId());

        //email
        $Sujet = "Votre inscription Allocab";

        $From  = "From:Thomas Tiercelin<thomas.tiercelin@allocab.com>\n";
        $From .= "MIME-version: 1.0\n";
        $From .= "Content-type: text/html; charset= iso-8859-1\n";

        $Message = <<<EOF
        <a href="http://www.allocab.com"><img border="0" src="http://www.allocab.com/logo_allocab.jpg" width="218" height="60" alt="Allocab - réservation de moto taxi en ligne"/></a>
        <p>Merci de la confiance que vous nous accordez.<br/>
        Vous trouverez ci-dessous vos identifiants pour vous connecter &agrave; la plateforme.<br/>
        Email : $email
        <br/>
        Mot de passe : $pass
        <br/><br/>
        A bient&ocirc;t sur <a href="http://www.allocab.com">Allocab</a>
        <br/>
        <br/>
        Cordialement,
        <br/>
        <b>Thomas Tiercelin</b><br/>
        <i>Co-fondateur Allocab</i>
        </p>


EOF;

        mail($email,$Sujet,$Message,$From);

        //sms
        $to = $this->getPhoneInternational();
        $message = "Votre mot de passe Allocab : ".$pass."";
        SmsClass::sendSms($to, $message);
    }

    return parent::save($con);
  }

} // DriverCustomer
