<?php


/**
 * Skeleton subclass for performing query and update operations on the 'driver_account' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb  5 09:57:11 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DriverAccountPeer extends BaseDriverAccountPeer {

} // DriverAccountPeer
