<?php


/**
 * Skeleton subclass for performing query and update operations on the 'fare_request' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb 26 13:28:04 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FareRequestPeer extends BaseFareRequestPeer {

    static function retrieveByHash($hash) {
    $c = new Criteria();
    $c->add(FareRequestPeer::HASH, $hash);
    $Fare_request = FareRequestPeer::doSelectOne($c);

    return $Fare_request;
}

} // FareRequestPeer
