<?php


/**
 * Skeleton subclass for performing query and update operations on the 'fare' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/01/11 10:34:31
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FarePeer extends BaseFarePeer {

    static function retrieveByHash($hash) {
    $c = new Criteria();
    $c->add(FarePeer::HASH, $hash);
    $Fare = FarePeer::doSelectOne($c);

    return $Fare;
}

    static function getIncomingFares($driver) {

        $c = new Criteria();
        $c->add(FarePeer::DRIVER_ID, $driver->getId());
        $c->add(FarePeer::DATETIME, date('Y-m-d H:i:s'), Criteria::GREATER_THAN);
        $c->addAscendingOrderByColumn(FarePeer::DATETIME);
        $Fares = FarePeer::doSelect($c);

        return $Fares;
    }

    static function getPendingFares($driver) {

        $c = new Criteria();
        $c->add(FarePeer::DRIVER_ID, $driver->getId());
        $c->add(FarePeer::DATETIME, date('Y-m-d H:i:s'), Criteria::LESS_THAN);
        $c->add(FarePeer::DONE, 0);
        $c->addAscendingOrderByColumn(FarePeer::DATETIME);
        $Fares = FarePeer::doSelect($c);

        return $Fares;
    }

    static function getDoneFares($driver) {

        $c = new Criteria();
        $c->add(FarePeer::DRIVER_ID, $driver->getId());
        $c->add(FarePeer::DATETIME, date('Y-m-d H:i:s'), Criteria::LESS_THAN);
        $c->add(FarePeer::DONE, 1);
        $c->addAscendingOrderByColumn(FarePeer::DATETIME);
        $Fares = FarePeer::doSelect($c);

        return $Fares;
    }

} // FarePeer
