<?php


/**
 * Skeleton subclass for representing a row from the 'location' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Mar  4 23:23:33 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Location extends BaseLocation {

  public function __toString()
  {
    return $this->getAdress();
  }

    static public function storeLocation($adress) {
        $c = new Criteria();
        $c->add(LocationPeer::ADRESS,$adress);
        $location = LocationPeer::doSelectOne($c);
        
        if($location) {
            $location->setCount($location->getCount()+1);
            $location->save();
        }
        else {

        $location = new Location();
        $location->setAdress($adress);
        $location->save();
        }
    }

} // Location
