<?php


/**
 * Skeleton subclass for representing a row from the 'password_retrieve' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Mar 11 16:43:39 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PasswordRetrieve extends BasePasswordRetrieve {

  public function save(PropelPDO $con = null)
  {

      $token = sha1(Tools::random(15));
      $this->setToken($token);
      return parent::save($con);
  }

} // PasswordRetrieve
