<?php


/**
 * Skeleton subclass for performing query and update operations on the 'password_retrieve' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Mar 11 16:43:39 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PasswordRetrievePeer extends BasePasswordRetrievePeer {

    public static function retrieveByToken($token) {

        $c = new Criteria();
        $c->add(PasswordRetrievePeer::TOKEN, $token);
        $PasswordRetrieve = PasswordRetrievePeer::doSelectOne($c);

        return $PasswordRetrieve;
    }

} // PasswordRetrievePeer
