<?php


/**
 * Skeleton subclass for representing a row from the 'prime' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Feb  5 16:17:40 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Prime extends BasePrime {

} // Prime
