# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Allocab - Chauffeur
    description:  Interface mobile des Moto Taxis
    #keywords:     symfony, project
    language:     fr
    robots:       noindex, nofollow

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
