# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Allocab | Interface de gestion
    description:  Interface de gestion de votre compte Allocab
    #keywords:     symfony, project
    language:     fr
    robots:       noindex, nofollow

  stylesheets:    [driver/reset.css,driver/main.css,driver/2col.css,driver/style.css,driver/mystyle.css]

  javascripts:    [driver/jquery.js,driver/switcher.js,driver/toggle.js,driver/ui.core.js,driver/ui.tabs.js]

  has_layout:     true
  layout:         layout
